services:
  soullink-tracker:
    image: ghcr.io/joos-too/soullink-tracker:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-Soullink-Tracker}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8067}:80"
    volumes:
      - maintenance:/maintenance
    labels:
      - "ubuntu"

volumes:
  maintenance:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAINTENANCE_DIR:-/home/ubuntu/Docker/Webserver/Soullink/maintenance}
